namespace SourceGenerator;

public static class Constants
{
    public const string CspMixinAttributeFullName =
        "NetEscapades.AspNetCore.SecurityHeaders.Headers.ContentSecurityPolicy.CspMixinAttribute";

    public const string Header =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated by a source generator
        //
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------

        #nullable enable

        """;
}