language: csharp
sudo: required
dist: trusty
env:
  - CLI_VERSION="latest"
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
dotnet: 1.0.3
mono:
  - 4.2.3
os:
  - linux
  - osx
osx_image: xcode7.1
branches:
  only:
    - master
script:
  - ./build.sh