version: '{build}'
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
branches:
  only:
  - master
clone_depth: 1
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.snupkg
  name: NuGet Symbols
deploy:
- provider: NuGet
  server: https://www.myget.org/F/andrewlock-ci/api/v2/package
  api_key:
    secure: 7XbdNq38u0JLRNc9pRl35WPi5LZopfYcoCslf7Er/eTreR5mZnGbmY/lVQYcgxI2
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: VGNbtH6ABQ090Qmi26swEiewS3RRGuCNUvj56/YJ9XufUWzWg1pzYajVVeIjMhg8
  on:
    branch: master
    appveyor_repo_tag: true