name: BuildAndPack

on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: windows
            vm: windows-latest
          - os: linux
            vm: ubuntu-latest
          - os: macos
            vm: macos-13  # latest is arm64, and it breaks a bunch of stuff
    env:
      MSBuildEnableWorkloadResolver: false
    name: ${{ matrix.os}}
    runs-on: ${{ matrix.vm}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
            6.0.x
            3.1.x
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Run './build.cmd Test Pack PushToNuGet GenerateSbom'
        run: ./build.cmd Test Pack PushToNuGet GenerateSbom
        env:
          GithubToken: ${{ secrets.GITHUB_TOKEN }}
          NuGetToken: ${{ secrets.NUGET_TOKEN }}
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows' }}
        with:
          name: packages
          path: artifacts/packages

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.os == 'windows' }}
        with:
          name: sboms
          path: artifacts/sboms

      - uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.os}}
          path: artifacts/results

  generate-attestations-and-release:
    name: "Generate attestations and Create Release"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write # write required for release creation
      attestations: write

    steps:
      - uses: actions/checkout@v4
      - name: Download Sboms
        uses: actions/download-artifact@v4
        with:
          name: sboms
          path: artifacts/sboms

      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: artifacts/packages

      - name: Attest package
        uses: actions/attest-sbom@v2
        id: nupkg-sbom
        with:
          subject-path: artifacts/packages/NetEscapades.AspNetCore.SecurityHeaders.?.?.*.nupkg
          sbom-path: artifacts/sboms/netescapades-aspnetcore-securityheaders.bom.json

      - name: Attest taghelpers
        uses: actions/attest-sbom@v2
        id: taghelpers-sbom
        with:
          subject-path: artifacts/packages/NetEscapades.AspNetCore.SecurityHeaders.TagHelpers.*.nupkg
          sbom-path: artifacts/sboms/netescapades-aspnetcore-securityheaders-taghelpers.bom.json

      - name: Generate artifact attestation
        id: artifact-attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'artifacts/packages/*.nupkg'

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          body_path: ReleaseNotes.md
          files: |
            artifacts/packages/*.nupkg
            artifacts/sboms/netescapades-aspnetcore-securityheaders.bom.json
            artifacts/sboms/netescapades-aspnetcore-securityheaders-taghelpers.bom.json

      - name: Update Release with attestations
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          body: |
            
            All NuGet packages are available on https://www.nuget.org.
            You can view the provenance attestation for the packages at ${{ steps.artifact-attestation.outputs.attestation-url }}.

            To verify the provenance for a given downloaded NuGet package, you can use the GitHub CLI:

            ```bash
            gh attestation verify --owner andrewlock <filename-or-url>
            ```
            
            The Software Bill of Materials (SBOM) is available for each package in CycloneDX format, and is attached to the relase.
            View the provenance attestation for the NetEscapades.AspNetCore.SecurityHeaders SBOM at ${{ steps.nupkg-sbom.outputs.attestation-url }}.
            and for the NetEscapades.AspNetCore.SecurityHeaders.TagHelpers SBOM at ${{ steps.taghelpers-sbom.outputs.attestation-url }}.
            

  publish-test-results:
    name: "Publish Tests Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write # needed unless run with comment_mode: off
      # contents: read # only needed for private repository
      # issues: read # only needed for private repository
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/results

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "artifacts/**/*.trx"
          json_thousands_separator: ","
          check_run_annotations_branch: "*"