name: BuildAndPack

on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - os: windows
            vm: windows-latest
          - os: linux
            vm: ubuntu-latest
          - os: macos
            vm: macos-13  # latest is arm64, and it breaks a bunch of stuff
    env:
      MSBuildEnableWorkloadResolver: false
    name: ${{ matrix.os}}
    runs-on: ${{ matrix.vm}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
            6.0.x
            3.1.x
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Run './build.cmd Test Pack PushToNuGet'
        run: ./build.cmd Test Pack PushToNuGet
        env:
          GithubToken: ${{ secrets.GITHUB_TOKEN }}
          NuGetToken: ${{ secrets.NUGET_TOKEN }}
          DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "true"

      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.os}}
          path: artifacts/packages